version: '2'

services:
  reverseproxy:
    image: azureiotpcs/remote-monitoring-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
    volumes:
      - /app/certs:/app/certs:ro

  webui:
    image: azureiotpcs/pcs-remote-monitoring-webui:latest
    depends_on:
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
    volumes:
      - /app/webui-config.js:/app/build/config.js:ro

  auth:
    image: azureiotpcs/pcs-auth-dotnet
    environment:
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_APPLICATION_SECRET

  iothubmanager:
    image: azureiotpcs/iothub-manager-dotnet
    environment:
      - PCS_IOTHUB_CONNSTRING
      # TODO: the dependency on config is temporary
      - PCS_CONFIG_WEBSERVICE_URL=http://config:9005/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_APPLICATION_SECRET

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:latest
    depends_on:
      - storageadapter
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_APPLICATION_SECRET
    #volumes:
    #  - ./sample-volume:/app/data:ro

  telemetry:
    image: azureiotpcs/telemetry-dotnet:latest
    depends_on:
      - storageadapter
    environment:
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_APPLICATION_SECRET

  config:
    image: azureiotpcs/pcs-config-dotnet:latest
    depends_on:
      - storageadapter
      - devicesimulation
      - telemetry
      - iothubmanager
    environment:
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_DEVICESIMULATION_WEBSERVICE_URL=http://devicesimulation:9003/v1
      - PCS_TELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL=http://iothubmanager:9002/v1
      - PCS_BINGMAP_KEY
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_APPLICATION_SECRET

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-dotnet:latest
    environment:
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_APPLICATION_SECRET

  telemetryagent:
    # TODO: rename image to telemetry-agent-dotnet
    image: azureiotpcs/telemetry-agent-dotnet:latest
    depends_on:
      - telemetry
      - iothubmanager
      - config
    environment:
      - PCS_TELEMETRYAGENT_DOCUMENTDB_CONNSTRING
      - PCS_TELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_CONFIG_WEBSERVICE_URL=http://config:9005/v1
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL=http://iothubmanager:9002/v1
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_ACCESS_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_APPLICATION_SECRET
