version: '2'

services:
  reverseproxy:
    image: azureiotpcs/remote-monitoring-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - uiconfig
    volumes:
      - /app/certs:/app/certs:ro

  webui:
    image: azureiotpcs/pcs-remote-monitoring-webui:latest
    depends_on:
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - uiconfig
    volumes:
      - /app/webui-config.js:/app/build/config.js:ro

  auth:
    image: azureiotpcs/pcs-auth-dotnet
    environment:
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE

  iothubmanager:
    image: azureiotpcs/iothub-manager-dotnet
    depends_on:
      - uiconfig
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_UICONFIG_WEBSERVICE_URL=http://uiconfig:9005/v1

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:latest
    depends_on:
      - storageadapter
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
    #volumes:
    #  - ./sample-volume:/app/data:ro

  telemetry:
    image: azureiotpcs/device-telemetry-dotnet:latest
    depends_on:
      - storageadapter
    environment:
      - PCS_DEVICETELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1

  uiconfig:
    image: azureiotpcs/pcs-ui-config-dotnet:latest
    depends_on:
      - storageadapter
    environment:
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_BINGMAP_KEY

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-dotnet:latest
    environment:
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING

  telemetryagent:
    image: azureiotpcs/iot-stream-analytics-dotnet:latest
    depends_on:
      - telemetry
      - iothubmanager
      - uiconfig
    environment:
      - PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING
      - PCS_DEVICETELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_UICONFIG_WEBSERVICE_URL=http://uiconfig:9005/v1
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL=http://iothubmanager:9002/v1
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_ACCESS_CONNSTRING
